stages:
  - lint
  - format
  - sast
  - test

.lint:
  stage: lint
  image: python:<%= it.version %>
  needs: []
  script:
    - echo "Starting the Lint stage"
  only:
    refs:
      - branches
    changes:
      - "**/*.py"

.format:
  stage: format
  image: python:<%= it.version %>
  needs: []
  script:
    - echo "Starting the Format stage"
  only:
    refs:
      - branches
    changes:
      - "**/*.py"

.sast:
  stage: sast
  image: returntocorp/semgrep-agent:v1
  needs: ["format", "lint"]
  script:
    - echo "Starting the SAST stage"
  only:
    refs:
      - branches
    changes:
      - "**/*.py"

.test:
  stage: test
  image: python:<%= it.version %>
  needs: ["format", "lint"]
  script:
    - echo "Starting the Test stage"
  only:
    refs:
      - branches
    changes:
      - "**/*.py"

include:
<% if (it.linters) { -%>
  - local: ".gitlab-ci/pipelinit.python.lint.yaml"
<% } -%>
<% if (it.formatters) { -%>
  - local: ".gitlab-ci/pipelinit.python.format.yaml"
<% } -%>
<% if (it.frameworks.django || it.hasPytest) { -%>
  - local: ".gitlab-ci/pipelinit.python.test.yaml"
<% } -%>
  - local: ".gitlab-ci/pipelinit.python.sast.yaml"
