stages:
  - lint
  - format
  - sast
  - test

include:
<% if (it.linters) { -%>
  - local: ".gitlab-ci/pipelinit.python.lint.yaml"
<% } -%>
<% if (it.formatters) { -%>
  - local: ".gitlab-ci/pipelinit.python.format.yaml"
<% } -%>
<% if (it.frameworks.django || it.hasPytest) { -%>
  - local: ".gitlab-ci/pipelinit.python.test.yaml"
<% } -%>
  - local: ".gitlab-ci/pipelinit.python.sast.yaml"
