name: Lint Terraform
on:
  pull_request:
    paths:
      - "**.tf"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set Up Terraform
        uses: hashicorp/setup-terraform@v1
        with:
            terraform-version: "<%= it.version.github %>"
      - run: terraform init
      - run: terraform validate
