name: Docker file Lint
on:
  pull_request:
    paths:
      - "**Dockerfile"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          for dockerfile in $(git ls-files **/*Dockerfile* Dockerfile)
          do
            echo "Starting lint for the Dockerfile $dockerfile"
            docker run --rm -i hadolint/hadolint < $dockerfile
          done
        shell: bash
