name: Release new version

on:
  push:
    tags:
      - "*.*.*"

env:
  GITHUB_REPOSITORY: ${{ github.repository }}

jobs:
  release:
    name: Build and publish new release
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set current version
        run: echo "RELEASE_VERSION=${GITHUB_REF#refs/*/}" >> $GITHUB_ENV
      - name: Set repository name
        run: echo "GITHUB_REPOSITORY=${GITHUB_REPOSITORY/*\/}" >> $GITHUB_ENV

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
<% it.registries.urls.forEach( function(url) { %>
      - name: Log in to the registry <%= url %>
        uses: docker/login-action@v1
        with:
          registry: <%= url %>
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_PASSWORD }}
<% it.dockerContext.paths.forEach( function(path) { %>
      <%_ let dockerfilePath = !path ? "" : "-" + path -%>
      - name: Extract metadata (tags, labels) <%= path %>
        id: meta<%= dockerfilePath %>
        uses: docker/metadata-action@v3
        with:
          tags: |
            type=semver,pattern={{version}},enable=true
          images: <%= url %>/${{ secrets.REGISTRY_ORGANIZATION }}/${{ env.GITHUB_REPOSITORY }}<%= dockerfilePath %>

      - name: Build and push Docker image <%= path %>
        uses: docker/build-push-action@v2
        with:
          build-args: "version=${{ env.RELEASE_VERSION }}"
          context: ./<%= path %>
          push: true
          tags: ${{ steps.meta<%= dockerfilePath %>.outputs.tags }}
          labels: ${{ steps.meta<%= dockerfilePath %>.outputs.labels }}
<% }) %>
<% }) %>