<% if (it.formatters) { -%>
name: Format Ruby
on:
  pull_request:
    paths:
      - "**.rb"
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: "<%= it.version %>"
          bundler-cache: true
<% if (!it.formatters.rubocop.isDependency) { -%>
      - run: gem install rubocop
<% } -%>
<% if (it.formatters.rubocop) { -%>
      - run: bundle exec rubocop --format .
<% } -%>
<%- } -%>