<% if (it.runtime.name === "deno") { -%>
name: Format Deno
on:
  pull_request:
    paths:
      - '**.js'
      - '**.ts'
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno fmt --check $(find . -iname "*.[j|t]s")
<% } else if (it.runtime.name === "node" && it.formatters) { -%>
name: Format JavaScript
on:
  pull_request:
    paths:
      - '**.js'
      - '**.ts'
jobs:
  format:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '<%= it.runtime.version.github %>'
          cache: '<%= it.packageManager.name %>'
      - run: <%= it.packageManager.commands.install %>
      <%_ if (it.formatters.prettier) { %>
      - run: npx prettier --no-error-on-unmatched-pattern --check "**/*.js" "**/*.ts"
      <% } -%>
<% } -%>
