<% if (it.runtime.name === "deno") { -%>
name: Lint Deno
on:
  pull_request:
    paths:
      - '**.js'
      - '**.ts'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno lint --unstable
<% } else if (it.runtime.name === "node" && it.linters) { -%>
name: Lint JavaScript
on:
  pull_request:
    paths:
      - '**.js'
      - '**.ts'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '<%= it.runtime.version %>'
          cache: '<%= it.packageManager.name %>'
      - run: <%= it.packageManager.commands.install %>
      <%_ if (it.linters.eslint) { %>
      - run: npx eslint --ext .js --ext .ts .
      <% } -%>
<% } -%>
