<% if (it.runtime.name === "deno") { -%>
name: Test Deno
on:
  pull_request:
    paths:
      - '**.js'
      - '**.ts'
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: denoland/setup-deno@v1
        with:
          deno-version: v1.x
      - run: deno test --unstable --allow-all
<% } -%>