stages:
  - lint
  - format
  - sast
  - test

.lint:
  stage: lint
  image: javascript:<%= it.version %>
  needs: []
  script:
    - echo "Starting the Lint stage"
  only:
    refs:
      - branches
    changes:
      - "**/*.js"
      - "**/*.ts"

.format:
  stage: format
  image: javascript:<%= it.version %>
  needs: []
  script:
    - echo "Starting the Format stage"
  only:
    refs:
      - branches
    changes:
      - "**/*.js"
      - "**/*.ts"

.sast:
  stage: sast
  image: returntocorp/semgrep-action@v1
  needs: ["format", "lint"]
  script:
    - echo "Starting the SAST stage"
  only:
    refs:
      - branches
    changes:
      - "**/*.js"
      - "**/*.ts"

.test:
  stage: test
  image: javascript:<%= it.version %>
  needs: ["format", "lint"]
  script:
    - echo "Starting the Test stage"
  only:
    refs:
      - branches
    changes:
      - "**/*.js"
      - "**/*.ts"

include:
<% if ((it.runtime.name === 'deno') || (it.runtime.name === 'node' && it.linters) || (it.hasTypeScriptFiles)) { -%>
    - local: ".gitlab-ci/pipelinit.javascript.lint.yaml"
<% } -%>
<% if ((it.runtime.name === 'deno') || (it.runtime.name === 'node' && it.formatters)) { -%>
    - local: ".gitlab-ci/pipelinit.javascript.format.yaml"
<% } -%>
<% if ((it.runtime.name === 'deno') || (it.runtime.name === 'node' && it.testCommand)) { -%>
    - local: ".gitlab-ci/pipelinit.javascript.test.yaml"
<% } -%>
    - local: ".gitlab-ci/pipelinit.javascript.sast.yaml"