<% if (it.runtime.name === "node" && it.formatters) { -%>
name: Format HTML
on:
  pull_request:
    paths:
      - '**.html'
      - '**.vue'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '<%= it.runtime.version.github %>'
          cache: '<%= it.packageManager.name %>'
      - run: <%= it.packageManager.commands.install %>
      <%_ if (it.formatters.prettier) { %>
      - run: npx prettier --no-error-on-unmatched-pattern --check "**/*.vue" "**/*.html"
      <% } -%>
<% } -%>
