<% if (it.runtime.name === "node" && it.linters && it.frameworks.vue) { -%>
name: Lint Vue
on:
  pull_request:
    paths:
      - '**.vue'
jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '<%= it.runtime.version.github %>'
          cache: '<%= it.packageManager.name %>'
      - run: <%= it.packageManager.commands.install %>
      <%_ if (it.linters.eslint) { %>
      - run: npx eslint --ext .vue .
      <% } -%>
      <%_ if (it.linters.styleLint) { %>
      - run: npx stylelint --aei **/*.vue
      <% } -%>
<% } -%>
