<% if (it.frameworks.django || it.hasPytest) { -%>
name: Test Python
on:
  pull_request:
    paths:
      - "**.py"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python <%= it.version %>
        uses: actions/setup-python@v2
        with:
          python-version: "<%= it.version %>"
<% if (it.packageManager) { -%>
      - run: <%= it.packageManager.commands.install %>
<% } -%>
<% if (it.hasPytest) { -%>
      - name: Pytest run
        run: |
          pytest
<% } -%>
<%_ if (it.frameworks.django) { %>
      - name: Run Tests
        run: |
          python manage.py test
<% } -%>
<% } -%>