name: Test Python
on:
  pull_request:
    paths:
      - "**.py"
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python <%= it.version %>
        uses: actions/setup-python@v2
        with:
          python-version: <%= it.version %>
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      <%_ if (it.django) { %>
      - name: Run Tests
        run: |
          python manage.py test
      <% } else { -%>
      - name: Test with pytest
        run: |
          pytest
      <% } -%>