name: Semgrep
on:
  pull_request:
    paths:
      - '**.js'
      - '**.ts'
jobs:
  semgrep:
    name: Scan
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: returntocorp/semgrep-action@v1
        with:
          config: p/dockerfile
